Howso:
  client: howso.direct.HowsoDirectClient
  client_extra_params:
     debug: true
     version_checks: false
     amalgam:
        library_postfix: -st
        trace: true
        execution_trace_dir: ./traces/