Howso:
  client: howso.direct.HowsoDirectClient
  client_extra_params:
     debug: True
     check_version: False 
     amalgam:
        library_postfix: -mt
        trace: True 
        execution_trace_dir: ./traces/
