name: "Frogbot Scan Pull Request"

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read
jobs:

  scan-pull-request:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Download Artifacts
        run: |
          mkdir -p dist
          pip download -r requirements-3.11.txt -d ./dist
          # Remove amalgam_lang and howso_openapi_client since we don't want these to be scanned
          rm -f ./dist/amalgam_lang*
          rm -f ./dist/howso_openapi_client*

      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_ALLOWED_LICENSES: "Apache-1.0, Apache-1.1, Apache-2.0, Artistic-1.0, Artistic-1.0-Perl, Artistic-2.0, BSD, BSD 2-Clause, BSD 3-Clause, BSD-2-Clause, BSD-3-Clause, MIT, MPL-2.0"

      - name: 🐸 scan
        run: |
          jf s ./dist/ --licenses --watches pipeline-distributed