name: Reusable WF - Output Workflow Summary

on:
  workflow_call:
    inputs:
      payload:
        type: string
        required: true
      build-type:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:

  get-amalgam-lang-py-details:
    uses: "./.github/workflows/get-dependency-details.yml"
    secrets: inherit
    with:
      owner: "howsoai"
      repo: "amalgam-lang-py"
      payload: "${{ inputs.payload }}"
      skip-version-json-check: true

  output-summary:
    needs: ["get-amalgam-lang-py-details"]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./tmp

      - name: Clean up dir
        run: |
          mkdir -p dist
          mkdir -p hse
          find ./tmp -type f -name '*.whl' -exec mv -t ./hse {} +

      - name: Download amalgam-lang-py
        if: needs.get-amalgam-lang-py-details.outputs.run-type != ''
        env:
          GH_TOKEN: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
        run: |
          gh ${{ needs.get-amalgam-lang-py-details.outputs.run-type }} download -D amlg -R "howsoai/amalgam-lang-py" -p "amalgam_lang-*-py3-none-any" "${{ needs.get-amalgam-lang-py-details.outputs.run-id }}"
          # Needed because release/non-release downloads are different structure
          cd amlg && if [ ! -f *.whl ]; then mv */*.whl ./; fi

      - name: Generate workflow summary
        env:
          GH_TOKEN: ${{ secrets.HOWSOAI_WORKFLOW_AUTOMATION_TOKEN }}
        run: |
          # Determine site-packages location
          site_packages=$(python -m site --user-site)

          # Install requirements
          pip install -e . --user
          pip uninstall howso-engine -y
          pip install hse/*-py3-none-any.whl --user
          pip uninstall amalgam-lang -y
          # Be sure to install the none-any version
          pip install amalgam-lang --platform none --no-deps --target $site_packages
          if [ -d "amlg" ]; then
            echo "Found custom amalgam-lang version; installing..."
            pip uninstall amalgam-lang -y
            pip install amlg/*.whl --user
          fi

          # Get amalgam metadata from version.json
          amlg_version=$(jq -r '.version.amalgam' $site_packages/amalgam/lib/version.json)
          amlg_sha=$(jq -r '.version."amalgam_sha"' $site_packages/amalgam/lib/version.json)
          amlg_url=$(jq -r '.version."amalgam_url"' $site_packages/amalgam/lib/version.json)
          if [[ $(cat $site_packages/amalgam/lib/version.json | jq '.version | has("amalgam_build_date")') == true ]]; then
            # Version is a prerelease (workflow run)
            build_date=$(jq -r '.version."amalgam_build_date"' $site_packages/amalgam/lib/version.json)
            build_date=$(python -c "from datetime import datetime; print(datetime.strptime('$build_date', '%Y-%m-%dT%H:%M:%SZ').strftime('%A, %B %d, %I:%M %p'))")
            amlg_notes=$(jq -r '.version."amalgam_display_title"' $site_packages/amalgam/lib/version.json)
            amlg_notes=$(python -c "notes = '$amlg_notes'.split(' -')[0] if 'PR Build' in '$amlg_notes' else '$amlg_notes'; print(notes)")
            amlg_version=$(echo "$amlg_version ($build_date)")
          else
            # Version is a release
            amlg_notes=$(echo "Release version embedded in the installed \`amalgam-lang-py\`")
          fi
          # Substitute info into version_summary.md
          sed -i "s|{amalgam-version}|$amlg_version|g" ./.github/templates/version_summary.md
          sed -i "s|{amalgam-notes}|$amlg_notes|g" ./.github/templates/version_summary.md
          sed -i "s|{amalgam-sha}|$amlg_sha|g" ./.github/templates/version_summary.md
          sed -i "s|{amalgam-url}|$amlg_url|g" ./.github/templates/version_summary.md

          # Get howso-engine metadata from version.json
          hse_version=$(jq -r '."version"' $site_packages/howso/howso-engine/version.json)
          hse_sha=$(jq -r '."sha"' $site_packages/howso/howso-engine/version.json)
          hse_url=$(jq -r '."url"' $site_packages/howso/howso-engine/version.json)
          if [[ $(cat $site_packages/howso/howso-engine/version.json | jq '. | has("build_date")') == true ]]; then
            # Version is a prerelease (workflow run)
            build_date=$(jq -r '."build_date"' $site_packages/howso/howso-engine/version.json)
            build_date=$(python -c "from datetime import datetime; print(datetime.strptime('$build_date', '%Y-%m-%dT%H:%M:%SZ').strftime('%A, %B %d, %I:%M %p'))")
            hse_notes=$(jq -r '."display_title"' $site_packages/howso/howso-engine/version.json)
            hse_notes=$(python -c "notes = '$hse_notes'.split(' -')[0] if 'PR Build' in '$hse_notes' else '$hse_notes'; print(notes)")
            hse_version=$(echo "$hse_version ($build_date)")
          else
            # Version is a release
            hse_notes=$(echo "Release version specified in \`version.json\`")
          fi
          # Substitute info into version_summary.md
          sed -i "s|{howso-engine-version}|$hse_version|g" ./.github/templates/version_summary.md
          sed -i "s|{howso-engine-notes}|$hse_notes|g" ./.github/templates/version_summary.md
          sed -i "s|{howso-engine-sha}|$hse_sha|g" ./.github/templates/version_summary.md
          sed -i "s|{howso-engine-url}|$hse_url|g" ./.github/templates/version_summary.md

          # Get amalgam-lang-py metadata from workflow run or release install
          pkg_version=$(python -c "import importlib.metadata; print(importlib.metadata.version('amalgam-lang'))")
          run_id=${{ needs.get-amalgam-lang-py-details.outputs.run-id }}
          if [[ "${{ needs.get-amalgam-lang-py-details.outputs.run-type }}" == "run" ]]; then
            build_date=$(gh run view --repo howsoai/amalgam-lang-py $run_id --json createdAt | jq '.createdAt')
            build_date=$(python -c "from datetime import datetime; print(datetime.strptime($build_date, '%Y-%m-%dT%H:%M:%SZ').strftime('%A, %B %d, %I:%M %p'))")
            branch=$(gh run view --repo howsoai/amalgam-lang-py $run_id --json headBranch | jq '.headBranch')
            pkg_notes=$(echo "Branch build of \`$branch\`")
            pkg_version=$(echo "$pkg_version ($build_date)")
            pkg_sha=$(gh run view --repo howsoai/amalgam-lang-py $run_id --json headSha | jq '.headSha')
            pkg_url=$(gh run view --repo howsoai/amalgam-lang-py $run_id --json url | jq '.url')
          else
            pkg_notes=$(echo "Release version specified in Python requirements")
            pkg_sha=$(gh release view --repo howsoai/amalgam-lang-py $run_id --json targetCommitish | jq '.targetCommitish')
            pkg_url=$(gh release view --repo howsoai/amalgam-lang-py $run_id --json url | jq '.url')
          fi
          sed -i "s|{amalgam-lang-py-version}|$pkg_version|g" ./.github/templates/version_summary.md
          sed -i "s|{amalgam-lang-py-notes}|$pkg_notes|g" ./.github/templates/version_summary.md
          sed -i "s|{amalgam-lang-py-sha}|$pkg_sha|g" ./.github/templates/version_summary.md
          sed -i "s|{amalgam-lang-py-url}|$pkg_url|g" ./.github/templates/version_summary.md

          # Remove unecessary quotations from variable substitutions
          sed -i "s|\"||g" ./.github/templates/version_summary.md
          # Output filled template file to workflow summary
          cat ./.github/templates/version_summary.md >> $GITHUB_STEP_SUMMARY